/**
 * Created by tillkolter on 19/03/17.
 */

export const SET_CART = 'SET_CART'
export const SET_USER = 'SET_USER'
export const SET_USER_ARTISTS = 'SET_USER_ARTISTS'
export const SET_USER_PAYMENT_METHODS = 'SET_USER_PAYMENT_METHODS'
export const SET_USER_SHIPPING_ADDRESSES = 'SET_USER_SHIPPING_ADDRESSES'
export const SET_USER_BILLING_ADDRESSES = 'SET_USER_BILLING_ADDRESSES'
export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS'
export const SET_SHIPPING_ADDRESS_CONFIRMED = 'SET_SHIPPING_ADDRESS_CONFIRMED'
export const SET_BILLING_ADDRESS = 'SET_BILLING_ADDRESS'
export const UPDATE_USER_ARTIST = 'UPDATE_USER_ARTIST'
export const SET_SHIPPING_OPTIONS = 'SET_SHIPPING_OPTIONS'
export const SET_SHIPPING_OPTION = 'SET_SHIPPING_OPTION'
export const SET_PAYMENT_OPTION_CONFIRMED = 'SET_PAYMENT_OPTION_CONFIRMED'
export const SET_SELECTED_PAYMENT_OPTION = 'SET_SELECTED_PAYMENT_OPTION'
export const SET_UNPAID_ORDER = 'SET_UNPAID_ORDER'

export const LOGOUT_USER = 'LOGOUT_USER'
export const CART_UPDATING = 'CART_UPDATING'

export const PLAY_TRACK = 'PLAY_TRACK'
export const SET_PLAYLIST_VISIBLE = 'SET_PLAYLIST_VISIBLE'
export const PAUSE_TRACK = 'PAUSE_TRACK'
export const ADD_TRACK = 'ADD_TRACK'
export const PLAY_BACKWARD = 'PLAY_BACKWARD'
export const PLAY_FORWARD = 'PLAY_FORWARD'
export const ADD_ALERT = 'ADD_ALERT'

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const ADD_SEARCH_RESULTS = 'ADD_SEARCH_RESULTS'
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING'
export const SET_QUERY = 'SET_QUERY'
export const INCREMENT_SEARCH_LOADING = 'INCREMENT_SEARCH_LOADING'
export const DECREMENT_SEARCH_LOADING = 'DECREMENT_SEARCH_LOADING'

export const ENTER_CHECKOUT = 'ENTER_CHECKOUT'
export const FINISH_CHECKOUT = 'FINISH_CHECKOUT'
export const SET_GUEST_CHECKOUT = 'SET_GUEST_CHECKOUT'
export const SET_CURRENT_CHECKOUT_STATE = 'SET_CURRENT_CHECKOUT_STATE'
export const SET_PAYMENT_OPTIONS = 'SET_PAYMENT_OPTIONS'
export const SET_SELECTED_PAYMENT_METHOD = 'SET_SELECTED_PAYMENT_METHOD'

export const SET_COUNTRIES = 'SET_COUNTRIES'

export const RESET_USER_DATA = 'RESET_USER_DATA'

export const SET_BILLING_ADDRESS_ID = 'SET_BILLING_ADDRESS_ID'
export const SET_SHIPPING_ADDRESS_ID = 'SET_SHIPPING_ADDRESS_ID'
export const SET_CHECKOUT_REGISTER_USER = 'SET_CHECKOUT_REGISTER_USER'

export const SET_USER_FORM_NAME_ERROR = 'SET_USER_FORM_NAME_ERROR'
export const SET_USER_FORM_PWD_ERROR = 'SET_USER_FORM_PWD_ERROR'
export const SET_USER_FORM_PWD_CONFIRM_ERROR = 'SET_USER_FORM_PWD_CONFIRM_ERROR'
export const SET_USER_FORM_EMAIL_ERROR = 'SET_USER_FORM_EMAIL_ERROR'

export const CHANGE_PAYMENT_METHOD = 'CHANGE_PAYMENT_METHOD'
export const CHANGE_BILLING = 'CHANGE_BILLING'
export const CHANGE_SHIPPING = 'CHANGE_SHIPPING'
export const CHANGE_SHIPPING_OPTION = 'CHANGE_SHIPPING_OPTION'
